<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What_q</name>
   <tag></tag>
   <elementGuidId>8af390cd-b188-4fc6-b188-7f130db21290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-what</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-input-what']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58d8f084-005e-4e42-8a67-67c0cc145107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8d9ea7f-0dbf-4e63-a7fb-cc68d123bf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label-text-input-what</value>
      <webElementGuid>4e5ea573-d8a7-4619-83a1-0d64b7a13d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-what</value>
      <webElementGuid>5142aafc-fe9c-4cf9-a5ca-7de51bea00f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>efbbcf10-1d67-4a39-8143-7f235c60753b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job title, keywords, or company</value>
      <webElementGuid>08ec5812-2e97-4898-8c2f-de31d84b0679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e07d519f-1140-45fb-ba5b-8569aa2690c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>text-input-what-suggestion-list</value>
      <webElementGuid>d424bc97-1b65-4b81-b6fc-b0eb30bf98f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icl-TextInput-control</value>
      <webElementGuid>5bd624af-b7ec-4335-849b-2a1dec89edb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f31bfdd-0b54-4202-817b-77c1446eb8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-what&quot;)</value>
      <webElementGuid>8e2f837d-8043-4cd6-ad7b-9baa092d77ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-input-what']</value>
      <webElementGuid>0d73c3f1-605e-4857-ada9-854578c1e159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='jobsearch']/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>4fdd139e-8feb-445b-8216-0e5732bc3c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8cdb75f6-4461-45de-8ef0-311396d233c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-input-what' and @name = 'q' and @placeholder = 'Job title, keywords, or company']</value>
      <webElementGuid>6cd6b697-6416-4f40-a129-09a89e97457c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
